 export const demandesDevis = [
    {
      id: "DEV-001",
      client: "Entreprise ABC",
      email: "contact@abc.com",
      produit: "Vitrage double",
      quantite: 50,
      montant: "15 000 €",
      date: "2026-01-15",
      statut: "en_attente",
    },
    {
      id: "DEV-002",
      client: "Société XYZ",
      email: "info@xyz.com",
      produit: "Vitrage sécurisé",
      quantite: 30,
      montant: "22 500 €",
      date: "2026-01-14",
      statut: "accepte",
    },
    {
      id: "DEV-003",
      client: "Construction Pro",
      email: "pro@construction.com",
      produit: "Vitrage isolant",
      quantite: 100,
      montant: "45 000 €",
      date: "2026-01-13",
      statut: "en_cours",
    },
    {
      id: "DEV-004",
      client: "Habitat Plus",
      email: "habitat@plus.com",
      produit: "Vitrage acoustique",
      quantite: 25,
      montant: "18 750 €",
      date: "2026-01-12",
      statut: "refuse",
    },
    {
      id: "DEV-005",
      client: "Rénovation SA",
      email: "contact@renovation.com",
      produit: "Vitrage anti-UV",
      quantite: 75,
      montant: "28 000 €",
      date: "2026-01-11",
      statut: "en_attente",
    },
  ];